# Generated by Django 3.1.1 on 2022-01-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='bathrooms',
            field=models.DecimalField(blank=True, decimal_places=1, default=1, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='bedrooms',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='video',
            name='garage',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='price',
            field=models.IntegerField(default=100000),
        ),
    ]
