# Generated by Django 3.1.1 on 2022-01-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20220115_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='bedrooms',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='price',
            field=models.IntegerField(blank=True, default=100000, null=True),
        ),
    ]
