# Generated by Django 3.1.1 on 2022-01-15 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20220115_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='city',
            field=models.CharField(blank=True, default='Anantapur', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='state',
            field=models.CharField(blank=True, default='Anantapur', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='zipcode',
            field=models.CharField(blank=True, default=515001, max_length=20, null=True),
        ),
    ]
