# Generated by Django 3.1.1 on 2022-06-12 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postad',
            name='ad_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
