# Generated by Django 3.1.1 on 2022-01-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='type',
            field=models.CharField(blank=True, default='Agri Land', max_length=200, null=True),
        ),
    ]
