# Generated by Django 3.1.1 on 2022-01-29 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='Latitude',
            field=models.DecimalField(blank=True, decimal_places=4, default=14.8008, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='Longitude',
            field=models.DecimalField(blank=True, decimal_places=4, default=77.598, max_digits=6, null=True),
        ),
    ]
