# Generated by Django 3.1.1 on 2022-01-31 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20220129_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='division',
            field=models.CharField(blank=True, default='ARM', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='type',
            field=models.CharField(blank=True, default='AL', max_length=200, null=True),
        ),
    ]
