# Generated by Django 3.1.1 on 2022-02-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20220131_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='mapframe',
            field=models.CharField(blank=True, default='MapFrame Tags', max_length=400, null=True),
        ),
    ]
