# Generated by Django 3.1.1 on 2022-02-05 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20220203_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='Latitude',
            field=models.DecimalField(blank=True, decimal_places=8, default=14.8008, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='Longitude',
            field=models.DecimalField(blank=True, decimal_places=8, default=77.598, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='bathrooms',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='bedrooms',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='lot_size',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
