# Generated by Django 3.2.13 on 2022-07-10 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20220629_0507'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='details',
            field=models.TextField(blank=True, default='Post Details', verbose_name='Details'),
        ),
    ]
